apiVersion: argoproj.io/v1alpha1     
kind: Rollout  
metadata:
  name: rollout-bluegreen
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        # image: argoproj/rollouts-demo:blue
        # image: argoproj/rollouts-demo:green
        image: jemesbond/angular:v2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active 
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
